//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupAdminTelegramBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BotResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GroupAdminTelegramBot.BotResources", typeof(BotResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام شما به دلیل داشتن تگ (نشانی کانال ها یا افراد) حذف شد، برای قرار دادن تگ باید دارای عضویت پرمیوم باشید و برای پرمیوم کردن عضویت خود باید 10 نفر را به این گروه بیفزایید. این کار را از طریق add member داخل گروه می توانید انجام دهید.
        /// </summary>
        internal static string BotForbidLinkResponse {
            get {
                return ResourceManager.GetString("BotForbidLinkResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با سلام 
        ///
        ///شما راهنمای بات را صدا زدید در این راهنما با دستورات بات و قابلیت های آن آشنا خواهیم شد.
        ///
        ///دستورات :
        ///-دستور /create _ selection به مدیر گروه اجازه ایجاد نظرسنجی را میدهد و تمامی کاربران میتوانند در نظرسنجی شرکت کنند
        ///-دستور /start _ election برای فعالسازی نظرسنجی بعد از انتخاب عنوان و گزینه ها می باشد.
        ///-دستور /set_silence_time و سپس بازه زمانی به شکل (19:00-20:00 ) برای فعال سازی ساعت سکوت است تا در ساعاتی مشخص کاربران اجازه صحبت کردن را نداشته باشند.
        ///-دستور /set_invite_link و سپس لینک گروه  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BotHelpText {
            get {
                return ResourceManager.GetString("BotHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا صبر کن تا گروه هایی که توشون عضوی رو بررسی کنم, پیشاپیش از صبرت ممنونم....
        /// </summary>
        internal static string BotInviteResponse1 {
            get {
                return ResourceManager.GetString("BotInviteResponse1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یکی از گروه های توی این لیست رو انتخاب کن:.
        /// </summary>
        internal static string BotInviteResponse2 {
            get {
                return ResourceManager.GetString("BotInviteResponse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای افزودن کاربر و ارتقا حساب اعضای گروه باید به صفحه بات (@bamahamyeshAdminBot) بروند و دستور /start و سپس /invite را بزنند. لیستی برای آنها تشکیل میشود که از داخل لیست اسم گروهی که میخواهند کاربر به آن بیافزاینده را کلیک کنند تا دگمه جدیدی ساخته شود.
        ///
        ///سپس روی دگمه جدید کلیک کنند و یکی از چت هایی که با دوستان خود داشته آن را انتخاب نمایند.
        ///
        ///سپس به صفحه دوست خود منتقل میشوند و اسم گروه بالای بخش چت نمایش داده می شود و با کلیک روی آن دگمه عضویت برای آنها ایجاد خواهد شد.
        /// </summary>
        internal static string BotInviteSystemHelpText {
            get {
                return ResourceManager.GetString("BotInviteSystemHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالا روی دگمه پایین کلیک کن و سپس یکی از چت های pv خودتو انتخاب کن تا دگمه عضویت تو صفحه دوستت هم تولید بشه.
        /// </summary>
        internal static string BotPickUserResponse {
            get {
                return ResourceManager.GetString("BotPickUserResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با تشکر از اینکه گروه خود را در این بات قراردادید برای کسب اطلاعات بیشتر در مورد نحوه افزودن کاربران جدید به گروه دستور /bot_invitation_tutorials رو وارد کنید..
        /// </summary>
        internal static string BotSetInviteLinkReponse {
            get {
                return ResourceManager.GetString("BotSetInviteLinkReponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سلام حالت چطوره؟
        ///لطفا یکی از دستورات زیر را انتخاب کن:
        ///دستور /invite برای دعوت کاربر جدید به گروه 
        ///دستور /stats برای دیدن تعداد افرادی که به گروه اضافه کردی.
        /// </summary>
        internal static string BotStartResponse {
            get {
                return ResourceManager.GetString("BotStartResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در لیست زیر امتیاز های شما در هر گروه نشان داده شده است :.
        /// </summary>
        internal static string BotStatsResponse2 {
            get {
                return ResourceManager.GetString("BotStatsResponse2", resourceCulture);
            }
        }
    }
}
